spring:
  application:
    name: bozorcheck
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
